name: Documentation
on: [push]

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
        persist-credentials: false

    - uses: nikeee/docfx-action@v1.0.0
      with:
        args: docs/docfx.json

    # Output
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_site  # The folder the action should deploy.
        TARGET_FOLDER: docs
